### ISSUE TITLE
Wrong Player # listed in controls panel

### ISSUE THREAD

**Issue by arevi** [arevi/Kill-Doctor-Lucky-Web-Port#1]
`          <p id="current-turn"></p>`

Lists the incorrect player as turns pass, most likely an issue with the way it is set in scripts.js

**Comment by arevi** [comment]
Issue has been fixed, moved the player indicator change event to occur at the beginning of renderMoveableRooms. This should address it not being set properly.

Commit: https://github.com/arevi/Kill-Doctor-Lucky-Web-Port/commit/046475f9692b412fa61060b19a757123f859720c

**Comment by aamo1** [comment]
Solution is effective

**Comment by n-k-dev** [comment]
Correct player appears to now be shown in control panel.
