### ISSUE TITLE
Player icon can be transparent

### ISSUE THREAD

**Issue by arevi** [arevi/Kill-Doctor-Lucky-Web-Port#2]
`  for (i = 0; i < gameData.playerCount; i++) {
    gameData.Players.push(
      new Player(i, '#' + (((1 << 24) * Math.random()) | 0).toString(16))
    );
  }`

When generating a color to represent the player, the color can be transparent. This affects the ability to see the player on the game board and leads them to only be represented by the player icon border.

**Comment by arevi** [comment]
```
const generateRandomColor = () => {
  let options = '0123456789ABCDEF';
  let color = '#';
  for (let index = 0; index < 6; index++) {
    color += options[Math.floor(Math.random() * 16)];
  }

  return color;
};
```

Added new generateRandomColor function which, hopefully, going forward should only generate valid hexadecimal color codes. Ideally, this should fix the issue of occasional transparency.

Commit: https://github.com/arevi/Kill-Doctor-Lucky-Web-Port/commit/3e2dbd0c08ff4e8a7cb0afa04a1f72fe69e5e363

**Comment by aamo1** [comment]
Cool solution, also tested this and verified that it works.

**Comment by n-k-dev** [comment]
Have not witnessed any transparent character emblems since testing this fix.
