### ISSUE TITLE
Kill button stays Active

### ISSUE THREAD

**Issue by arevi** [arevi/Kill-Doctor-Lucky-Web-Port#4]
In an online game session after the player has already failed a murder attempt, the kill button is still marked as active allowing them to attempt a second murder attempt.

**Comment by arevi** [comment]
The issue appears to have been addressed by Kren, I have tested in a local and online game. Unable to reproduce the bug after the latest commit.

https://github.com/arevi/Kill-Doctor-Lucky-Web-Port/commit/7a0a14f9943991486e2105d4e5120487e6927a29

**Comment by n-k-dev** [comment]
Corrected this issue; kill button should no longer stay active.

**Comment by aamo1** [comment]
Looks good!
