### ISSUE TITLE
Rooms that should be unvisitable, are marked as visitable

### ISSUE THREAD

**Issue by arevi** [arevi/Kill-Doctor-Lucky-Web-Port#6]
```
const renderMovableRooms = player => {
  renderPlayerCard(player);
  let playerLocation = player.location;
  rooms[playerLocation].visitableRooms.forEach(room => {
    let roomName = getRoomName(room);
    document.querySelector(`#${roomName}`).classList.add('possible-move');
    document
      .querySelector(`#${roomName}`)
      .addEventListener('click', movePlayer);
  });

  rooms[playerLocation].lineOfSight.forEach(room => {
    let roomName = getRoomName(room);
    document.querySelector(`#${roomName}`).classList.add('in-sight');
    document
      .querySelector(`#${roomName}`)
      .addEventListener('click', movePlayer);
  });
};
```

When the renderMovableRooms function is called, the correct rooms are highlighted with a green border signifying that they have a click handler on them. This click handler allows the player to move from room to room, however, some rooms that should not be visitable are also marked.

This is most likely an issue involving the rooms array, which is read to highlight visitable rooms depending on the player's location.

**Comment by arevi** [comment]
Identified that 
```
  rooms[playerLocation].lineOfSight.forEach(room => {
    let roomName = getRoomName(room);
    document.querySelector(`#${roomName}`).classList.add('in-sight');
    document
      .querySelector(`#${roomName}`)
      .addEventListener('click', movePlayer);
  });
```

was adding event handlers for movePlayer() to rooms with line of sight, the event handler should have only been added to visitable rooms.

**Comment by n-k-dev** [comment]
Tested in local and online play, and can no longer move to unvisitable rooms.

**Comment by aamo1** [comment]
Confirmed fixed
