### ISSUE TITLE
Incorrect round is displayed in controls Panel

### ISSUE THREAD

**Issue by arevi** [arevi/Kill-Doctor-Lucky-Web-Port#7]
The controls panel currently displays the incorrect rounds elapsed. This appears to be being incremented after each player turn and should only be incremented once the full group of players has had their turns elapse.

**Comment by arevi** [comment]
Updated the game logic to render the current round at the same time it renders possible moves on the game board, appears to be working properly online and locally now.

Commit: https://github.com/arevi/Kill-Doctor-Lucky-Web-Port/commit/ef24225257f821a78795e5794e5e36e02f0aec54

**Comment by n-k-dev** [comment]
Tested this in local play for 2 - 8 players.  Seems to be properly displaying round number and current player's turn.  Matt and I tested online with 2 players, which also appears to be accurate.

**Comment by n-k-dev** [comment]
Tested successfully 3 players in online mode.

**Comment by aamo1** [comment]
Good fix.
