### ISSUE TITLE
Create game increment/decrement buttons don't disappear after limit has reached

### ISSUE THREAD

**Issue by arevi** [arevi/Kill-Doctor-Lucky-Web-Port#8]
As recommended by Mr. Confer, the buttons in the create game menu do not disappear after a player has reached either the floor or ceiling of players allowed.

 This should be relatively straight forward to implement as the function already does check for the maximum/minimum being reached, a CSS selector for hiding the buttons will just need to be added.

**Comment by arevi** [comment]
Added a 'hidden' class to the style.css and implemented the logic to toggle this class name on the buttons depending on the current player count in the game creation menu.

Commit: https://github.com/arevi/Kill-Doctor-Lucky-Web-Port/commit/e9b02360d070aadaa0cd868124e5eb7620fc2f44

**Comment by aamo1** [comment]
This is a good idea, and good implementation
