### ISSUE TITLE
Room indicator for Dr. Lucky can overlap if the text spans 2 lines

### ISSUE THREAD

**Issue by arevi** [arevi/Kill-Doctor-Lucky-Web-Port#9]
If the text contained within the location panel, on the left side of the screen, spans 2 lines the text for Dr. Lucky's location will overlap and be unreadable. This is reflected in the image included below, this appears to be a CSS issue and should be fixable by modifying the CSS class for the location text.

![Issue](https://user-images.githubusercontent.com/42751430/68082847-be1b9300-fdef-11e9-8ac6-c96ef46e176d.png)

**Comment by arevi** [comment]
Pushed commit addressing text-overflow, introduced a new issue with the bottom player being out of bounds of the container if there are 8 players. Will have to be addressed later, don't expect 8 people to be playing this game.

Commit: https://github.com/arevi/Kill-Doctor-Lucky-Web-Port/commit/3f856603794bc865e83113c664fa8cd499b6e1c5

**Comment by aamo1** [comment]
This has been added as a constraint to the design doc
